/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthsync;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author ACER
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
        private static String loggedInUsername;

    public Dashboard(String username) {
        initComponents();
        this.loggedInUsername = username; // Store the username in the class variable
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        patients = new javax.swing.JLabel();
        diagnose = new javax.swing.JLabel();
        service = new javax.swing.JLabel();
        appointments = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dashpat = new javax.swing.JLabel();
        dashservice = new javax.swing.JLabel();
        dashapp = new javax.swing.JLabel();
        dashbapp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");

        patients.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        patients.setForeground(new java.awt.Color(255, 255, 255));
        patients.setText("Patients");
        patients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientsMouseClicked(evt);
            }
        });

        diagnose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        diagnose.setForeground(new java.awt.Color(255, 255, 255));
        diagnose.setText("Diagnoses");
        diagnose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diagnoseMouseClicked(evt);
            }
        });

        service.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        service.setForeground(new java.awt.Color(255, 255, 255));
        service.setText("Services");
        service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceMouseClicked(evt);
            }
        });

        appointments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        appointments.setForeground(new java.awt.Color(255, 255, 255));
        appointments.setText("Appointments");
        appointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentsMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patients, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diagnose)
                    .addComponent(service, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointments))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patients)
                .addGap(18, 18, 18)
                .addComponent(diagnose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(service)
                .addGap(18, 18, 18)
                .addComponent(appointments)
                .addGap(94, 94, 94)
                .addComponent(jLabel11)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Patients:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Services:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Appointments:");

        dashpat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dashpat.setForeground(new java.awt.Color(204, 0, 0));
        dashpat.setText("jLabel5");

        dashservice.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dashservice.setForeground(new java.awt.Color(204, 0, 0));
        dashservice.setText("jLabel6");

        dashapp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dashapp.setForeground(new java.awt.Color(204, 0, 0));

        dashbapp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dashbapp.setForeground(new java.awt.Color(204, 0, 0));
        dashbapp.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashservice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashpat)
                    .addComponent(dashbapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dashpat))
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dashservice))
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dashapp)
                    .addComponent(dashbapp))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Connection Con = null;
    private Statement St = null,St1 = null,St2 = null;
    private ResultSet Rs = null,Rs1 = null,Rs2 = null;
    private void getData() {
    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/healthsync", "root", "");

        // Prepare the statement with a parameter for the username
        PreparedStatement pstmt = Con.prepareStatement("SELECT COUNT(*) FROM pacienti WHERE numeutiliz = ?");
        pstmt.setString(1, loggedInUsername); // Assuming loggedInUser holds the username
        ResultSet rs = pstmt.executeQuery();

        PreparedStatement pstmt1 = Con.prepareStatement("SELECT COUNT(*) FROM servicii WHERE numeutiliz = ?");
        pstmt1.setString(1, loggedInUsername); // Assuming loggedInUser holds the username
        ResultSet rs1 = pstmt1.executeQuery();

        PreparedStatement pstmt2 = Con.prepareStatement("SELECT COUNT(*) FROM programari WHERE  numeutiliz = ?");
        pstmt2.setString(1, loggedInUsername); // Assuming loggedInUser holds the username
        ResultSet rs2 = pstmt2.executeQuery();

        while (rs.next()) {
            dashpat.setText("" + rs.getInt(1));
        }
        while (rs1.next()) {
            dashservice.setText("" + rs1.getInt(1));
        }
        while (rs2.next()) {
            dashbapp.setText("" + rs2.getInt(1));
        }

    } catch (SQLException ex) {
        // Handle your exception appropriately
    }
}

    private void patientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientsMouseClicked
        Patients patientPage= new Patients(loggedInUsername);
        patientPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_patientsMouseClicked

    private void diagnoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diagnoseMouseClicked
        Diagnose diagnosticPage = new Diagnose(loggedInUsername);
        diagnosticPage.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_diagnoseMouseClicked

    private void serviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceMouseClicked
        Serivces servicePage = new Serivces(loggedInUsername);
        servicePage.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_serviceMouseClicked

    private void appointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentsMouseClicked
        Appointments appPage= new Appointments(loggedInUsername);
        appPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appointmentsMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Login LoginPage= new Login();
        LoginPage.setVisible(true);
        this.dispose();     }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(loggedInUsername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointments;
    private javax.swing.JLabel dashapp;
    private javax.swing.JLabel dashbapp;
    private javax.swing.JLabel dashpat;
    private javax.swing.JLabel dashservice;
    private javax.swing.JLabel diagnose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel patients;
    private javax.swing.JLabel service;
    // End of variables declaration//GEN-END:variables
}
